import { defineConfig } from "@natsuneko-laboratory/makit";
import cloudflare from "@natsuneko-laboratory/makit-adapter-cloudflare-pages";

export default defineConfig({
  title: "Natsuneko Laboratory | Docs",
  description: "Documentation portal for Natsuneko Laboratory. This portal is generated by Makit.",
  dev: {
    silentNext: true
  },
  deployment: {
    adapter: cloudflare({
      projectName: "docs-natsuneko-cat",
      generateWranglerConfig: true,
    })
  },
  collections: {
    mode: "discover",
  },

  i18n: {
    defaultLocale: "ja-JP",
    locales: [
      { locale: "en-US", label: "English", },
      { locale: "ja-JP", label: "日本語", },
    ],
  },

  llms: {
    enabled: true,
  },
  github: {
    repository: "mika-f/docs.natsuneko.cat",
  },

  markdown: {
    tableOfContents: {
      minDepth: 2,
      maxDepth: 4,
    },
  },

  navigation: {
    global: [
      {
        title: "Resources",
        items: [
          { title: "GitHub", href: "https://github.com/natsuneko-laboratory", external: true },
        ],
      },
    ],
  },

  home: {
    layout: "portal",
    sections: [
      {
        title: {
          "en-US": "Consumer Products",
          "ja-JP": "コンシューマ向け製品"
        },
        collections: [
          "catalyst",
          "drag-and-drop-support",
          "epiclese",
          "floating-island",
          "nekodraw",
        ]
      },
      {
        title: {
          "en-US": "Developer Products",
          "ja-JP": "開発者向け製品"
        },
        collections: [
          "animation-auto-assignment",
          "animator-controller-tool-post-processing",
          "astro-notes",
          "checkout-lfs",
          "constraint-by-humanoid",
          "create-unitypackage",
          "create-vpmpackage",
          "otsukai",
          "plana",
          "text-mesh-creator",
          "udon-analyzer",
          "unitypackage",
          "ustyled",
          "vpmpackage",
        ],
      },
    ],
  },

  theme: {
    accentColor: "violet",
  },
});
