import type { Metadata } from "next";
import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { FALLBACK_LANGUAGE } from "@/configurations/i18n";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  params: Promise<{ lang: string }>;
  children: React.ReactNode;
};

export default async function RootLayout({ children, params }: Props) {
  const { lang } = await params;

  return (
    <>
      <Header lang={lang ?? FALLBACK_LANGUAGE} />
      <main>{children}</main>
      <Footer />
    </>
  );
}
